### ISSUE TITLE
Show the last failed script filename when migration failed

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#121]
When migration failed due to maybe erroneous script files, yuniql must show the file name where the issue is present. Right now, it only shows the error message like the case below. 

```
INF   2020-06-08T14:34:55.4200544Z   Found the 4 script files on /app/db/v0.00/05-views
INF   2020-06-08T14:34:55.4201147Z   001-assets.country_list.sql\r\n\t002-rawbased.service_flow_status_view.sql\r\n\t003-rawbased.uk_windfarms_view.sql\r\n\t004-rawbased.vol_cev_view.sql
INF   2020-06-08T14:34:55.4256065Z   Executed script file /app/db/v0.00/05-views/001-assets.country_list.sql.
INF   2020-06-08T14:34:55.4315773Z   Executed script file /app/db/v0.00/05-views/002-rawbased.service_flow_status_view.sql.
ERR   2020-06-08T14:34:55.4951396Z   Failed to execute run function. 
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'GO'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Yuniql.Core.ConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService) in C:\projects\yuniql\yuniql-core\ConnectionExtensions.cs:line 68
```

**Comment by rdagumampan** [comment]
Closed. This enhancement will be part of v1.0 release.
Errors will be displayed with better color coding and shows the last failed script file.

![image](https://user-images.githubusercontent.com/5895952/85934837-fc1e7780-b8e8-11ea-8f07-ded1952cd757.png)
