### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Robzilla** [rdagumampan/yuniql#144]
Hi, I am using PostGres PaaS in Azure. When SSL is enforced I get the following error (see below).
Any idea what the ssl is that the error eludes to?

ERR   2020-10-24 12:58:29Z   Failed to execute run function. Arrg... something seems broken.
Internal error message: Npgsql.PostgresException (0x80004005): 28000: SSL connection is required. Please specify SSL options and retry.
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Yuniql.Core.ConnectionExtensions.KeepOpen(IDbConnection connection) in C:\projects\yuniql\yuniql-core\ConnectionExtensions.cs:line 46
   at Yuniql.Core.ConnectionExtensions.QuerySingleBool(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService) in C:\projects\yuniql\yuniql-core\ConnectionExtensions.cs:line 127
   at Yuniql.Core.ConfigurationDataService.IsDatabaseExists(Nullable`1 commandTimeout) in C:\projects\yuniql\yuniql-core\ConfigurationDataService.cs:line 52
   at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Nullable`1 autoCreateDatabase, List`1 tokenKeyPairs, Nullable`1 verifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environmentCode, Nullable`1 
resumeFromFailure, Boolean noTransaction) in C:\projects\yuniql\yuniql-core\MigrationService.cs:line 101
   at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts) in C:\projects\yuniql\yuniql-cli\CommandLineService.cs:line 146
  Exception data:
    Severity: FATAL
    SqlState: 28000
    MessageText: SSL connection is required. Please specify SSL options and retry.
    File: auth.c
    Line: 481
    Routine: ClientAuthentication.
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.

**Comment by rubenamcruz** [comment]
Hi, on the database connection string you should indicate "Ssl Mode=Require;"
This way works for me.

**Comment by rdagumampan** [comment]
> Hi, on the database connection string you should indicate "Ssl Mode=Require;"
> This way works for me.

Thanks @rubenamcruz for your contribution. I hope this resolves @Robzilla' issue.

**Comment by rdagumampan** [comment]
Closing this in with possible solution suggested by @rubenamcruz. Please reopen if this ticket remain relevant and you have no fix around. Thanks for your feedback @Robzilla . Br, Rodel
