### ISSUE TITLE
`Parameter '@saved_cs_client' must be defined` error; syntax error near `DELIMITER`

### ISSUE THREAD

**Issue by DavidHopkinsFbr** [rdagumampan/yuniql#149]
Hi,

I'm trying out yuniql with a MariaDB target.

I have a database creation script that I generated using `MariaDB dump 10.17  Distrib 10.4.13-MariaDB, for Win64 (AMD64)`. This is the standard SQL dump tool for MariaDB/MySQL.

When I run the script against an empty database using the `mysql.exe` CLI, to create the database, it succeeds. 

But when I try `yuniql.exe run` to load the same script, it fails.

The error message is:
```
ERR   2020-12-15 08:13:36Z   Failed to execute run function. Arrg... something seems broken.
Internal error message: Fatal error encountered during command execution. Parameter '@saved_cs_client' must be defined..
```

The section of SQL which is triggering the error looks something like this (I've redacted application details):
```
--
-- Temporary table structure for view `mynewview`
--

DROP TABLE IF EXISTS `mynewview`;
/*!50001 DROP VIEW IF EXISTS `mynewview`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE TABLE `mynewview` (
  `Field1` tinyint NOT NULL,
  `Timestamp` tinyint NOT NULL,
  `Field2` tinyint NOT NULL,
  `Field3` tinyint NOT NULL,
  `Field4` tinyint NOT NULL
) ENGINE=MyISAM */;
SET character_set_client = @saved_cs_client;
```

Can you give me any hints why this standard dump file can be loaded using `mysql.exe` but not via yuniql?

**Comment by rdagumampan** [comment]
Hi @DavidHopkinsFbr  thanks for reaching out. I will try to reproduce this issue today and get back to you. Thanks also for your PRs, will review them this week. //Rodel

**Comment by rdagumampan** [comment]
I can't explain yet why it fail but I was able to reproduce the issue. It seems the sql statement is intact when it was executed and there was no fragmentation in the sql file. I will look further...

```console
docker run -dit --name mariadb -e MYSQL_ROOT_PASSWORD=P@ssw0rd! -d -p 3306:3306 mariadb:latest --default-authentication-plugin=mysql_native_password
SETX YUNIQL_CONNECTION_STRING "Server=localhost;Port=3306;Database=issue149;Uid=root;Pwd=P@ssw0rd!;"

C:\temp\issue-149>yuniql run -a --platform mariadb --debug
```
```console
Running yuniql v1.0.1 for windows-x64
Copyright 2019 (C) Rodel E. Dagumampan. Apache License v2.0
Visit https://yuniql.io for documentation & more samples

INF   2020-12-15 09:54:16Z   Started migration from C:\temp\issue-149.
...
...
INF   2020-12-15 09:54:17Z   Found 1 script files on C:\temp\issue-149
  + sample.sql
DBG   2020-12-15 09:54:17Z   Executing sql statement as part of : C:\temp\issue-149\v0.00\sample.sql
DBG   2020-12-15 09:54:17Z   Executing statement:
--
-- Temporary table structure for view `mynewview`
--

DROP TABLE IF EXISTS `mynewview`;
/*!50001 DROP VIEW IF EXISTS `mynewview`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE TABLE `mynewview` (
  `Field1` tinyint NOT NULL,
  `Timestamp` tinyint NOT NULL,
  `Field2` tinyint NOT NULL,
  `Field3` tinyint NOT NULL,
  `Field4` tinyint NOT NULL
) ENGINE=MyISAM */;
SET character_set_client = @saved_cs_client;
DBG   2020-12-15 09:54:17Z   Replaced YUNIQL_DB_NAME with issue149
DBG   2020-12-15 09:54:17Z   Replaced YUNIQL_SCHEMA_NAME with
DBG   2020-12-15 09:54:17Z   Replaced YUNIQL_TABLE_NAME with __yuniqldbversion
ERR   2020-12-15 09:54:17Z   Migration of "v0.00" version was not running in transaction and has failed when executing of script file "C:\temp\issue-149\v0.00\sample.sql" with following error: (0x80004005): Error Code: 0. Fatal error encountered during command execution. You must fix and execute the failed script manually and then run the migration with  "--continue-after-failure" argument. It will ensure that migration will skip this script and continue with next script.
ERR   2020-12-15 09:54:17Z   Failed to execute run function. Arrg... something seems broken.
Internal error message: MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered during command execution.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Parameter '@saved_cs_client' must be defined.
   at MySql.Data.MySqlClient.Statement.SerializeParameter(MySqlParameterCollection parameters, MySqlPacket packet, String parmName, Int32 parameterIndex)
   at MySql.Data.MySqlClient.Statement.InternalBindParameters(String sql, MySqlParameterCollection parameters, MySqlPacket packet)
   at MySql.Data.MySqlClient.Statement.BindParameters()
   at MySql.Data.MySqlClient.PreparableStatement.Execute()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
...
...
C:\temp\issue-149>
```

**Comment by DavidHopkinsFbr** [comment]
I've tried deleting various `character_set_client`, `character_set_results` and `collation_connection` local variable set/reset commands from my import script, since they're not really strictly necessary.

But after doing that, yuniql's internal MariaDB client connection seems to be having more syntax trouble. The latest error:
```
ERR   2020-12-16 02:05:13Z   Migration of "v0.00" version was not running in transaction and has failed when executing of script file "C:\git\yuniql-hadrian\v0.00\01-init.sql" with following error: (0x80004005): Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER ;;
/*!50003 CREATE*/ /*!50003 TRIGGER after_insert_item_state
        AFT' at line 1 You must fix and execute the failed script manually and then run the migration with  "--continue-after-failure" argument. It will ensure that migration will skip this script and continue with next script.
ERR   2020-12-16 02:05:13Z   Failed to execute run function. Arrg... something seems broken.
Internal error message: MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DELIMITER ;;
/*!50003 CREATE*/ /*!50003 TRIGGER after_insert_item_state
        AFT' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Yuniql.Core.ConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.ConfigurationDataService.ExecuteSql(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.NonTransactionalMigrationService.<>c__DisplayClass11_1.<RunSqlScripts>b__3(String sqlStatement)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.NonTransactionalMigrationService.<>c__DisplayClass11_0.<RunSqlScripts>b__1(String scriptFile)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.NonTransactionalMigrationService.RunSqlScripts(IDbConnection connection, IDbTransaction transaction, NonTransactionalContext nonTransactionalContext, String version, String workingPath, String scriptDirectory, String metaSchemaName, String metaTableName, List`1 tokenKeyPairs, Nullable`1 commandTimeout, String environmentCode, String appliedByTool, String appliedByToolVersion)
   at Yuniql.Core.NonTransactionalMigrationService.<>c__DisplayClass10_0.<RunVersionScripts>g__RunVersionScriptsInternal|3(IDbTransaction transaction, List`1 scriptSubDirectories, String scriptDirectory, String versionDirectory, String schemaName, String tableName)
   at Yuniql.Core.NonTransactionalMigrationService.<>c__DisplayClass10_0.<RunVersionScripts>b__2(String versionDirectory)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.NonTransactionalMigrationService.RunVersionScripts(IDbConnection connection, IDbTransaction transaction, List`1 dbVersions, String workingPath, String targetVersion, NonTransactionalContext nonTransactionalContext, List`1 tokenKeyPairs, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environmentCode)
   at Yuniql.Core.NonTransactionalMigrationService.<Run>g__RunAllInternal|9_3(IDbConnection connection, IDbTransaction transaction, <>c__DisplayClass9_0& )
   at Yuniql.Core.NonTransactionalMigrationService.Run(String workingPath, String targetVersion, Nullable`1 autoCreateDatabase, List`1 tokenKeyPairs, Nullable`1 verifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environmentCode, Nullable`1 nonTransactionalResolvingOption, Boolean noTransaction)
   at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts).
```

I've tried removing the conditional execution comments (e.g. `/*!50001 someSQL */`) but that doesn't make any difference.  It seems to be choking on the `DELIMITER ;;` statement. I've also tried changing the `DELIMITER ;;` statement to use a different character sequence, e.g. `DELIMITER //` as shown in the [MariaDB documentation example](https://mariadb.com/kb/en/delimiters/)

You can probably reproduce by putting the following SQL code into a script file:
```
DELIMITER //
SELECT TRUE//
DELIMITER ;
SELECT FALSE;
```

It looks like this might be related to [this](https://bugs.mysql.com/bug.php?id=46429).

Also [this StackOverflow question](https://stackoverflow.com/questions/52437944/how-to-use-delimiter-in-mariadb-using-the-net-mysql-connector) suggests that the connector's `MySqlScript` class might be more compatible with `mysqldump` output than `MySqlCommand` is.

**Comment by DavidHopkinsFbr** [comment]
I think the `@saved_cs_client` issue might have something to do with this note I found in the documentation for [`MySqlCommand`](https://dev.mysql.com/doc/dev/connector-net/8.0/html/T_MySql_Data_MySqlClient_MySqlCommand.htm) class:

> Using the '@' symbol for paramters is now the preferred approach although the old pattern of using '?' is still supported. Please be aware though that using '@' can cause conflicts when user variables are also used. To help with this situation please see the documentation on the 'allow user variables' connection string option. The 'old syntax' connection string option has now been deprecated.

Looks like the relevant documentation on the connector AllowUserVariables switch is [here](https://mysqlconnector.net/connection-options/).

**Comment by DavidHopkinsFbr** [comment]
Ok. Adding `AllowUserVariables=True` to my connection string is confirmed to fix all the `Parameter '@saved_cs_client' must be defined` errors.

Deleting all the `DELIMITER` statements and replacing all the customised `;;` delimiters in the dumpfile with `;` seems to address the delimiter compatibility problem, but it would be nice if yuniql could directly consume the output of `mysqldump` without needing to manually edit the file for compatibility.

**Comment by rdagumampan** [comment]
@DavidHopkinsFbr , sorry that's its taking time to look at the outstanding issues and I really appreciate that you are able to solve the issue anyway. Recent months has been not easy finding quite time to focus.

Agree, the intent of yuniql is to allow users to use best baseline facility and just drop the file into v0.00 directory. This has not been the case for mariadb. I think yuniql should also cover a direct dump test on all platforms supported as part of plarform test.

Im closing this ticket now and created https://github.com/rdagumampan/yuniql/issues/150
