### ISSUE TITLE
Unable to connect to server when there is no access to Master DB

### ISSUE THREAD

**Issue by larsoleruben** [rdagumampan/yuniql#17]
Stacktrace

`c:\Temp\yuniql-nightly>yuniqlx baseline -c "Server=XXXXXX;Initial Catalog=XXXXX;Persist Security Info=False;User ID=XXXXX;Password=XXXXX;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" -p "C:\Temp\yuniql-nightly\v0.00"
ERR   2019-11-01T14:26:59.6347662Z   Failed to execute init function.
Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server obs-sqlserver-dev.database.windows.net,1433.
 ---> System.Data.SqlClient.SqlException (0x80131904): The server principal "obsdbraw_adm" is not able to access the database "master" under the current security context.
Cannot open user default database. Login failed.
Login failed for user 'obsdbraw_adm'.
   at System.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
ClientConnectionId:c4c09285-30df-4cc9-80a6-b6660e86a1e4
Error Number:916,State:2,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at ArdiLabs.Yuniql.Extensions.BaselineService.Init(String connectionString)
   at ArdiLabs.Yuniql.Extensions.BaselineService.Run(String sourceConnectionString, String destinationFullPath)
   at ArdiLabs.Yuniql.Extensions.Program.RunBaselineOption(BaselineOption opts)
Unhandled exception. Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server obs-sqlserver-dev.database.windows.net,1433.
 ---> System.Data.SqlClient.SqlException (0x80131904): The server principal "obsdbraw_adm" is not able to access the database "master" under the current security context.`

**Comment by rdagumampan** [comment]
The issue seems to be connected to behaviour of SMO when connecting to Az SQL Databases. `yuniqlx` uses SQL Server SMO behind the scene and as this SO issue states, it automatically switches to `master` when I tried to capture the source database.

```csharp
server = new Server(connection);
//server auto switch to master after this line
database = server.Databases[connectionStringBuilder.InitialCatalog];
```
https://stackoverflow.com/questions/5798187/failure-to-create-table-in-sql-azure-database-using-smo

will try to reproduce the error.

**Comment by rdagumampan** [comment]
I am able to reproduce this now by creating a contained user on Azure SQL Database. We can resolve this by giving CONNECT grant to the contained user. The CONNECT grant is very limited permission level.

My recommendation is to create a dedicated `migrationagent` contained user with login grant in `master`. Until Microsoft released a fix in SMO's ServerConnection object.

1. First I created a login in `master`

```
--execute this in master db
CREATE LOGIN migrationagent WITH PASSWORD='supersecretpassword';
```
2.  Then create contained user from login and give access to user db

```sql
--execute this in user db: testazsqldb
CREATE USER migrationagent FROM LOGIN migrationagent
ALTER ROLE db_owner ADD MEMBER migrationagent
```

3.  Grant CONNECT permission to user. Without this, the migration would throw exception described in the issue.

```sql
--execute this in master db
CREATE USER migrationagent FROM LOGIN migrationagent
```

To view permissions granted at `master`

```sql
SELECT DISTINCT pr.principal_id, pr.name, pr.type_desc, 
    pr.authentication_type_desc, pe.state_desc, pe.permission_name
FROM sys.database_principals AS pr
JOIN sys.database_permissions AS pe
    ON pe.grantee_principal_id = pr.principal_id;

0	public	DATABASE_ROLE	NONE	GRANT	EXECUTE
0	public	DATABASE_ROLE	NONE	GRANT	SELECT
9	migrationagent	SQL_USER	INSTANCE	GRANT	CONNECT
```

HTH
