### ISSUE TITLE
Azure SQL Database already exists but yuniql attempts to re-create

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#18]
```csharp


SELECT ISNULL(DB_ID (N'testsql'),0);
INF   2019-11-03T12:16:51.9723644Z   Target database does not exist. Creating database testsql on tcp:testsqlrddag.database.windows.net,1433.
DBG   2019-11-03T12:16:51.9741370Z   Executing sql statement:
CREATE DATABASE testsql;
ERR   2019-11-03T12:16:52.7862509Z   Failed to execute run function. Target database will be rolled back to its previous state.
System.Data.SqlClient.SqlException (0x80131904): CREATE DATABASE permission denied in database 'master'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at ArdiLabs.Yuniql.DbHelper.ExecuteNonQuery(String connectionString, String sqlStatement) in C:\play\yuniql\src\DbHelper.cs:line 21
   at ArdiLabs.Yuniql.MigrationService.CreateDatabase(String targetDatabaseName) in C:\play\yuniql\src\MigrationService.cs:line 149
   at ArdiLabs.Yuniql.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokens, Boolean verificationRunOnly) in C:\play\yuniql\src\MigrationService.cs:line 36
   at ArdiLabs.Yuniql.Program.RunMigration(RunOption opts) in C:\play\yuniql\src\Program.cs:line 161
ClientConnectionId:96a2a90c-fd37-4a5a-bb2a-49953600f231
Error Number:262,State:1,Class:14
```

**Comment by rdagumampan** [comment]
**Investigation notes**
When running migration using `yuniql run -a`, it checks if the database already exists and attempts to create the target database if not. It uses `DB_ID()` function of sql server which is reported to be unreliable way of getting db existence checks in Azure SQL Database. 

**Resolution***
Refactored all existing queries using functions such as `DB_ID` and `OBJECT_ID` to use strong named containers such as `sys.databases` and `sys.tables`.

References:<br>
https://social.technet.microsoft.com/Forums/en-US/20791489-fad8-4469-98f5-1749d9450949/database-id-gets-changed?forum=ssdsgetstarted
