### ISSUE TITLE
Failed pipeline with error "...yuniql\0.0.0\x64\yuniql.exe' failed with exit code 1"

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#210]
![image](https://user-images.githubusercontent.com/31841996/125802838-57429d95-d021-471b-b56e-f7ae1059981e.png)
Hi @rdagumampan while setting up PostgreSQL Azure release am facing this error 
below is my connection string please help me 
Server=ella.db.elephantsql.com, Port=5432;Database=wlwvedlt; User ID=wlwvedlt; Password=xxxxxx;

__Originally posted by @Naimishah in https://github.com/rdagumampan/yuniql/issues/47#issuecomment-880731540__

**Comment by rdagumampan** [comment]
Hi @naimisha, thanks for reaching out. Can you paste the full log? It seems it doesn recognize your connection string. Try to runalso from local console.

**Comment by Naimishah** [comment]
2021-07-15T10:01:59.1873327Z ##[section]Starting: Run Yuniql
2021-07-15T10:01:59.2027600Z ==============================================================================
2021-07-15T10:01:59.2027936Z Task         : Run yuniql
2021-07-15T10:01:59.2028256Z Description  : Runs database migrations with Yuniql CLI using version acquired from Use Yuniql task.
2021-07-15T10:01:59.2028558Z Version      : 1.190.0
2021-07-15T10:01:59.2028797Z Author       : Rodel E. Dagumampan
2021-07-15T10:01:59.2029100Z Help         : https://yuniql.io/docs/migrate-via-azure-devops-pipelines/
2021-07-15T10:01:59.2029440Z ==============================================================================
2021-07-15T10:01:59.5131309Z yuniql/input_version: latest
2021-07-15T10:01:59.5132806Z yuniql/input_workspacePath: PostgresDemo\samples\basic-postgresql-sample
2021-07-15T10:01:59.5134256Z yuniql/input_connectionString: Server=ella.db.elephantsql.com, Port=5432;Database=wlwvedlt; User ID=wlwvedlt; Password=G7HaU-zTjvgd5kI1F3t576XruLSiipvd;
2021-07-15T10:01:59.5135236Z yuniql/input_targetPlatform: postgresql
2021-07-15T10:01:59.5135793Z yuniql/input_autoCreateDatabase: false
2021-07-15T10:01:59.5136127Z yuniql/input_targetVersion: v0.00
2021-07-15T10:01:59.5136485Z yuniql/input_tokenKeyValuePair: undefined
2021-07-15T10:01:59.5136806Z yuniql/input_delimiter: ,
2021-07-15T10:01:59.5137127Z yuniql/input_additionalArguments: --debug
2021-07-15T10:01:59.5137999Z yuniql/var_osPlat: win32
2021-07-15T10:01:59.5138705Z yuniql/var_osArch: x64
2021-07-15T10:01:59.5173891Z Found tool in cache: yuniql 0.0.0 x64
2021-07-15T10:01:59.5174617Z yuniql/var_yuniqlBasePath: C:\hostedtoolcache\windows\yuniql\0.0.0\x64
2021-07-15T10:01:59.5175215Z yuniql/var_yuniqlExecFilePath: C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe
2021-07-15T10:01:59.5201896Z yuniql/additionalArguments array is
2021-07-15T10:01:59.5202270Z arg#0: --debug
2021-07-15T10:01:59.5243932Z [command]C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe run -p PostgresDemo\samples\basic-postgresql-sample -c "Server=ella.db.elephantsql.com, Port=5432;Database=wlwvedlt; User ID=wlwvedlt; Password=G7HaU-zTjvgd5kI1F3t576XruLSiipvd;" --platform postgresql -t v0.00 --bulk-separator , --debug
2021-07-15T10:01:59.7968615Z Running yuniql v1.1.55 for windows-x64
2021-07-15T10:01:59.7972304Z Copyright 2019 (C) Rodel E. Dagumampan. Apache License v2.0
2021-07-15T10:01:59.7995058Z Visit https://yuniql.io for documentation & more samples
2021-07-15T10:01:59.7995754Z 
2021-07-15T10:01:59.8751800Z INF   2021-07-15 10:01:59Z   Run configuration: 
2021-07-15T10:01:59.8761648Z {
2021-07-15T10:01:59.8762320Z   "isInitialized": true,
2021-07-15T10:01:59.8763006Z   "workspace": "PostgresDemo\\samples\\basic-postgresql-sample",
2021-07-15T10:01:59.8763664Z   "platform": "postgresql",
2021-07-15T10:01:59.8764328Z   "connectionString": "<sensitive-data-redacted>",
2021-07-15T10:01:59.8766490Z   "isAutoCreateDatabase": false,
2021-07-15T10:01:59.8767060Z   "targetVersion": "v0.00",
2021-07-15T10:01:59.8767596Z   "tokens": [],
2021-07-15T10:01:59.8768207Z   "isVerifyOnly": false,
2021-07-15T10:01:59.8770394Z   "bulkSeparator": ",",
2021-07-15T10:01:59.8795430Z   "bulkBatchSize": 0,
2021-07-15T10:01:59.8798259Z   "commandTimeout": 30,
2021-07-15T10:01:59.8801852Z   "isDebug": true,
2021-07-15T10:01:59.8802375Z   "appliedByTool": "yuniql-cli",
2021-07-15T10:01:59.8802919Z   "appliedByToolVersion": "1.1.55.0",
2021-07-15T10:01:59.8803509Z   "environment": null,
2021-07-15T10:01:59.8805494Z   "metaSchemaName": null,
2021-07-15T10:01:59.8806061Z   "metaTableName": null,
2021-07-15T10:01:59.8809074Z   "isContinueAfterFailure": false,
2021-07-15T10:01:59.8809609Z   "transactionMode": "session",
2021-07-15T10:01:59.8810106Z   "isRequiredClearedDraft": false,
2021-07-15T10:01:59.8810553Z   "isForced": false
2021-07-15T10:01:59.8810910Z }
2021-07-15T10:02:00.0874639Z DBG   2021-07-15 10:02:00Z   Replaced token YUNIQL_DB_NAME with wlwvedlt
2021-07-15T10:02:00.0876065Z DBG   2021-07-15 10:02:00Z   Replaced token YUNIQL_SCHEMA_NAME with public
2021-07-15T10:02:00.0878301Z DBG   2021-07-15 10:02:00Z   Replaced token YUNIQL_TABLE_NAME with __yuniql_schema_version
2021-07-15T10:02:00.0955790Z DBG   2021-07-15 10:02:00Z   Executing statement D6F1F8: 
2021-07-15T10:02:00.0956634Z 
2021-07-15T10:02:00.0957184Z SELECT 1 FROM pg_tables WHERE  tablename = '__yuniql_schema_version';
2021-07-15T10:02:00.0957717Z             
2021-07-15T10:02:00.5659636Z ERR   2021-07-15 10:02:00Z   Failed to execute run function. No such host is known.
2021-07-15T10:02:00.5660567Z Diagnostics stack trace captured a System.Net.Sockets.SocketException (11001): 
2021-07-15T10:02:00.5671196Z    at System.Net.Dns.InternalGetHostByName(String hostName)
2021-07-15T10:02:00.5672184Z    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
2021-07-15T10:02:00.5673611Z    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
2021-07-15T10:02:00.5674528Z    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
2021-07-15T10:02:00.5675476Z    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
2021-07-15T10:02:00.5676075Z    at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
2021-07-15T10:02:00.5676747Z    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
2021-07-15T10:02:00.5677221Z --- End of stack trace from previous location where exception was thrown ---
2021-07-15T10:02:00.5678368Z    at Npgsql.NpgsqlConnection.Open()
2021-07-15T10:02:00.5678780Z    at Yuniql.Core.ConnectionExtensions.KeepOpen(IDbConnection connection)
2021-07-15T10:02:00.5679374Z    at Yuniql.Core.ConnectionExtensions.QuerySingleBool(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
2021-07-15T10:02:00.5680047Z    at Yuniql.Core.MetadataService.IsDatabaseConfigured(String metaSchemaName, String metaTableName, Nullable`1 commandTimeout)
2021-07-15T10:02:00.5681150Z    at Yuniql.Core.MigrationService.Run(String workspace, String targetVersion, Nullable`1 isAutoCreateDatabase, List`1 tokens, Nullable`1 isVerifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, Nullable`1 isContinueAfterFailure, String transactionMode, Boolean isRequiredClearedDraft)
2021-07-15T10:02:00.5682281Z    at Yuniql.Core.MigrationService.Run()
2021-07-15T10:02:00.5682659Z    at Yuniql.CLI.CommandLineService.RunRunOption(RunOption opts)
2021-07-15T10:02:00.5683184Z If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.
2021-07-15T10:02:00.5741779Z 
2021-07-15T10:02:00.5836329Z yuniql/error: The process 'C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe' failed with exit code 1
2021-07-15T10:02:00.5880751Z ##[error]The process 'C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe' failed with exit code 1
2021-07-15T10:02:00.5902824Z ##[section]Finishing: Run Yuniql

**Comment by Naimishah** [comment]
@rdagumampan sent the full log, will try to execute from the local console, and will let you know.

**Comment by rdagumampan** [comment]
Hi @Naimishah, I still looking forward for your feedback on this. If this remains an issue, please tag me along in your comment. Thank you for your support. HTH/Rodel

**Comment by rdagumampan** [comment]
Hi @Naimishah, I still looking forward for your feedback on this. Closing for now.
If this remains an issue, please tag me along in your comment. Thank you for your support. HTH/Rodel
