### ISSUE TITLE
Permission issue when executing certain commands on Postgres SQL migration

### ISSUE THREAD

**Issue by aimanuslim** [rdagumampan/yuniql#211]
Hi,

I am running yuniql with a local docker postgres setup this way

```
docker run -d --name postgres-for-yuniql -e POSTGRES_DB=mydatabase -v C:\Users\AIMMU\repos\postgres_data:/var/lib/postgresql/data -p 5431:5432 postgres
SETX YUNIQL_CONNECTION_STRING "Host=localhost;Port=5431;Username=orchestration;Password=password;Database=mydatabase"
SETX YUNIQL_WORKSPACE "C:\Users\AIMMU\repos\yuniql_poc"
SETX YUNIQL_PLATFORM "postgresql"
```

I am encountering issues when trying to migrate using certain SQL commands specifically this part (Sql command has been setup in v0.0 folder in the workspace)

`CREATE SCHEMA orchestration;`

Error is as shown below.. (earlier parts of sql are retracted)

```
...
CREATE SCHEMA orchestration;


-- ALTER SCHEMA orchestration OWNER TO orchestration;

ERR   2021-08-04 01:26:14Z   Failed to execute run function. Migration of version v0.00 was running in transaction and has failed while attempting to execute script file C:\Users\AIMMU\repos\yuniql_poc\v0.00\setup-orchestration-step1.sql due to error "(0x80004005) Error 42501: permission denied for database mydatabase. Exception data: Severity: ERROR, InvariantSeverity: ERROR, SqlState: 42501, MessageText: permission denied for database mydatabase, File: aclchk.c, Line: 3466, Routine: aclcheck_error". The target database will initiate a rollback attempt to revert all applicable DML and DDL changes. The database auto-created will be kept but would be empty.
Diagnostics stack trace captured a Yuniql.Core.YuniqlMigrationException:
 ---> Npgsql.PostgresException (0x80004005): 42501: permission denied for database mydatabase
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Yuniql.Core.ConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.MetadataService.ExecuteSql(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.MigrationService.<>c__DisplayClass15_1.<RunVersionSqlScripts>b__3(String sqlStatement)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.<>c__DisplayClass15_0.<RunVersionSqlScripts>b__1(String scriptFile)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.RunVersionSqlScripts(IDbConnection connection, IDbTransaction transaction, TransactionContext transactionContext, Stopwatch stopwatch, String version, String workspace, String scriptDirectory, String metaSchemaName, String metaTableName, List`1 tokens, Nullable`1 commandTimeout, String environment, String appliedByTool, String appliedByToolVersion)
  Exception data:
    Severity: ERROR
    SqlState: 42501
    MessageText: permission denied for database mydatabase
    File: aclchk.c
    Line: 3466
    Routine: aclcheck_error
   --- End of inner exception stack trace ---
   at Yuniql.Core.MigrationService.RunVersionSqlScripts(IDbConnection connection, IDbTransaction transaction, TransactionContext transactionContext, Stopwatch stopwatch, String version, String workspace, String scriptDirectory, String metaSchemaName, String metaTableName, List`1 tokens, Nullable`1 commandTimeout, String environment, String appliedByTool, String appliedByToolVersion)
   at Yuniql.Core.MigrationService.<>c__DisplayClass12_0.<RunVersionDirectories>g__RunVersionDirectoriesInternal|3(IDbConnection connection, IDbTransaction transaction, List`1 scriptSubDirectories, String scriptDirectory, String versionDirectory, Stopwatch stopwatch)
   at Yuniql.Core.MigrationService.<>c__DisplayClass12_0.<RunVersionDirectories>b__2(String versionDirectory)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.RunVersionDirectories(IDbConnection connection, IDbTransaction transaction, List`1 appliedVersions, String workspace, String targetVersion, TransactionContext transactionContext, List`1 tokens, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, String transactionMode)
   at Yuniql.Core.MigrationService.<Run>g__RunAllInternal|11_3(IDbConnection connection, IDbTransaction transaction, Boolean isRequiredClearedDraft, <>c__DisplayClass11_0& )
   at Yuniql.Core.MigrationService.Run(String workspace, String targetVersion, Nullable`1 isAutoCreateDatabase, List`1 tokens, Nullable`1 isVerifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, Nullable`1 isContinueAfterFailure, String transactionMode, Boolean isRequiredClearedDraft)
   at Yuniql.Core.MigrationService.Run()
   at Yuniql.CLI.CommandLineService.RunRunOption(RunOption opts)
```

The user `orchestration `has been created on the database as a superuser however when yuniql is executed, its complaining about not having permission.

**Comment by aimanuslim** [comment]
Hi a few updates on this.

I have a few lines before the above sql statement that looks like this:

```
CREATE ROLE dbadmin CREATEDB CREATEROLE;
CREATE ROLE azure_pg_admin;
...
SET ROLE dbadmin;
```

which seem to have set the user yuniql is using as agent to have the role of dbadmin. As you can see , the dbadmin role should have the permissions to `CREATEDB `and `CREATEROLE `but maybe that is not enough, and that maybe the cause of` CREATE SCHEMA` not succeeding.

If I switch `SET ROLE` to `orchestration` then it is able to execute the `CREATE SCHEMA` command. So it could be that dbadmin role does not have enough permission to proceed with the rest of the SQL statements. (`orchestration` as a user has superuser permissions and is also the owner of `mydatabase`)
