### ISSUE TITLE
Failed migration

### ISSUE THREAD

**Issue by avengerovsky** [rdagumampan/yuniql#217]
Several times my migrations failed with the following message: 
ERR   2021-11-04 03:15:10Z   Failed to execute run function. This NpgsqlTransaction has completed; it is no longer usable.
In all cases, yuniql doesn't create a record in the log (__yuniql_schema_version)

Note, that I noticed that in all cases there is a CREATE INDEX transaction (different in each case) in my script which takes some time to execute. When I execute the same script outside of migration scope it executes to completion. Don't know if this observation helps but wanted to share it anyway.

Full trace is here:

ERR   2021-11-04 03:15:10Z   Failed to execute run function. This NpgsqlTransaction has completed; it is no longer usable.
Diagnostics stack trace captured a System.InvalidOperationException: 
   at Npgsql.NpgsqlTransaction.CheckCompleted()
   at Npgsql.NpgsqlTransaction.CheckReady()
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Yuniql.Core.MigrationService.Run(String workspace, String targetVersion, Nullable`1 isAutoCreateDatabase, List`1 tokens, Nullable`1 isVerifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, Nullable`1 isContinueAfterFailure, String transactionMode, Boolean isRequiredClearedDraft)
   at Yuniql.Core.MigrationService.Run()
   at Yuniql.CLI.CommandLineService.RunRunOption(RunOption opts)
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.

**Comment by rdagumampan** [comment]
@avengerovsky, thanks for reaching out. I've seen this issue before and found it very difficult to reproduce. I was suspecting it maybe the open transaction was in some weird way was AUTOCOMMITed or implicitly committed. This results in the open transaction no longer available in the next batch of statements.

I hope you can try what happens if the data in the transaction CREATEINDEX is smaller. Also try to set the `--command-timeout 0` so its unlimited just to try this out.

**Comment by avengerovsky** [comment]
your suggestion worked - thank you! by the way, if I set timeout parameters
in the db connection string will it have the same effect?

**Comment by rdagumampan** [comment]
@avengerovsky, the connection object takes the connection string parameter value as-is so I assume it would have the same effect. I have no investigated if yuniql overrides this value. Closing this case now. Thanks for your contribution //~Rodel
