### ISSUE TITLE
How do I connect to a particular Schema?

### ISSUE THREAD

**Issue by shaileshsolanki16** [rdagumampan/yuniql#278]
Hello Rodel! 

I added as string Schema=<schemaname> while setting up the environment variable SETX YUNIQL_CONNECTION_STRING="Host=localhost;Port=5432;Username=<uname>;Password=<passwd>;Database=<dbname>;Schema=<schemaname>"

Below is the error and I think it is due to the addtional string Schema=<schamename> in the connection string. Please let me know how do i mention the schema name.

ERR   2022-07-04 14:06:18Z   Failed to execute run function. Couldn't set schema (Parameter 'schema')
Diagnostics stack trace captured a System.ArgumentException:
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Npgsql.NpgsqlConnectionStringBuilder.GeneratedSetter(String keyword, Object value)
   at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
   --- End of inner exception stack trace ---
   at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
   at Yuniql.PostgreSql.PostgreSqlDataService.GetConnectionInfo()
   at Yuniql.Core.MigrationService.Run(String workspace, String targetVersion, Nullable`1 isAutoCreateDatabase, List`1 tokens, Nullable`1 isVerifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, Nullable`1 isContinueAfterFailure, String transactionMode, Boolean isRequiredClearedDraft)
   at Yuniql.Core.MigrationService.Run()
   at Yuniql.CLI.CommandLineService.RunRunOption(RunOption opts)
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.

Thank you,
Shailesh

**Comment by rdagumampan** [comment]
Hi @shaileshsolanki16 , thanks for reaching out! Im not sure I follow your use case but you its about setting up one database with multiple schema, please explore this option in local or test database and let me know.

https://github.com/rdagumampan/yuniql/releases/tag/v1.2.25
