### ISSUE TITLE
SqlException (0x80131904): USE statement is not supported to switch between databases

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#29]
Exception is thrown when tested in Azure Sql Database when running migration in Azure DevOps Pipelines.
Source: YUNIQL Azure DevOps Tasks
Az DevOps Task: v0.9.0
Yuniql version: latest

```console
2019-12-19T23:21:39.4356069Z ##[section]Starting: run
2019-12-19T23:21:39.4478768Z ==============================================================================
2019-12-19T23:21:39.4478887Z Task         : Run YUNIQL CLI
2019-12-19T23:21:39.4478948Z Description  : Run YUNIQL CLI
2019-12-19T23:21:39.4479130Z Version      : 0.9.0
2019-12-19T23:21:39.4479188Z Author       : Rodel E. Dagumampan
2019-12-19T23:21:39.4479270Z Help         : This runs database migration with yuniql-cli
2019-12-19T23:21:39.4479340Z ==============================================================================
2019-12-19T23:21:39.7248593Z Run is executed
2019-12-19T23:21:39.7249018Z versionSpec: latest
2019-12-19T23:21:39.7284534Z Found tool in cache: yuniql 0.0.0 x64
2019-12-19T23:21:39.7321173Z [command]C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe run -p d:\a\1\s\sqlserver-samples\visitph-db -c "Server=tcp:azsql-sandbox.database.windows.net,1433;Initial Catalog=azsql-sandbox;Persist Security Info=False;User ID=rdagumampan;Password=XXXXXXX;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" -a false --debug
2019-12-19T23:21:41.1624068Z INF   2019-12-19T23:21:41.1550456Z   Started migration from d:\a\1\s\sqlserver-samples\visitph-db.
2019-12-19T23:21:41.1644140Z INF   2019-12-19T23:21:41.1550456Z   Started migration from d:\a\1\s\sqlserver-samples\visitph-db.
2019-12-19T23:21:41.1939587Z INF   2019-12-19T23:21:41.1933217Z   No explicit target version requested. We'll use latest available locally v1.01 on d:\a\1\s\sqlserver-samples\visitph-db.
2019-12-19T23:21:41.1940163Z INF   2019-12-19T23:21:41.1933217Z   No explicit target version requested. We'll use latest available locally v1.01 on d:\a\1\s\sqlserver-samples\visitph-db.
2019-12-19T23:21:41.3546801Z DBG   2019-12-19T23:21:41.3542376Z   Executing sql statement: 
2019-12-19T23:21:41.3547188Z SELECT ISNULL(database_id,0) FROM [sys].[databases] WHERE name = 'azsql-sandbox'
2019-12-19T23:21:41.3548640Z DBG   2019-12-19T23:21:41.3542376Z   Executing sql statement: 
2019-12-19T23:21:41.3548948Z SELECT ISNULL(database_id,0) FROM [sys].[databases] WHERE name = 'azsql-sandbox'
2019-12-19T23:21:41.7413269Z DBG   2019-12-19T23:21:41.7408044Z   Executing sql statement: 
2019-12-19T23:21:41.7413795Z SELECT ISNULL(object_id,0) FROM [sys].[tables] WHERE name = '__YuniqlDbVersion'
2019-12-19T23:21:41.7414085Z DBG   2019-12-19T23:21:41.7408044Z   Executing sql statement: 
2019-12-19T23:21:41.7414287Z SELECT ISNULL(object_id,0) FROM [sys].[tables] WHERE name = '__YuniqlDbVersion'
2019-12-19T23:21:41.9484309Z INF   2019-12-19T23:21:41.9475347Z   Target database azsql-sandbox on tcp:azsql-sandbox.database.windows.net,1433 not yet configured for migration.
2019-12-19T23:21:41.9485578Z INF   2019-12-19T23:21:41.9475347Z   Target database azsql-sandbox on tcp:azsql-sandbox.database.windows.net,1433 not yet configured for migration.
2019-12-19T23:21:41.9490658Z DBG   2019-12-19T23:21:41.9486542Z   Executing sql statement: 
2019-12-19T23:21:41.9491041Z 
2019-12-19T23:21:41.9491209Z                     USE azsql-sandbox;
2019-12-19T23:21:41.9491338Z 
2019-12-19T23:21:41.9491469Z                     IF OBJECT_ID('[dbo].[__YuniqlDbVersion]') IS NULL 
2019-12-19T23:21:41.9491622Z                     BEGIN
2019-12-19T23:21:41.9491758Z 	                    CREATE TABLE [dbo].[__YuniqlDbVersion](
2019-12-19T23:21:41.9491915Z 		                    [Id] [SMALLINT] IDENTITY(1,1),
2019-12-19T23:21:41.9492055Z 		                    [Version] [NVARCHAR](32) NOT NULL,
2019-12-19T23:21:41.9492209Z 		                    [DateInsertedUtc] [DATETIME] NOT NULL,
2019-12-19T23:21:41.9492357Z 		                    [LastUpdatedUtc] [DATETIME] NOT NULL,
2019-12-19T23:21:41.9492517Z 		                    [LastUserId] [NVARCHAR](128) NOT NULL,
2019-12-19T23:21:41.9492654Z 		                    [Artifact] [VARBINARY](MAX) NULL,
2019-12-19T23:21:41.9492814Z 		                    CONSTRAINT [PK___YuniqlDbVersion] PRIMARY KEY CLUSTERED ([Id] ASC),
2019-12-19T23:21:41.9492981Z 		                    CONSTRAINT [IX___YuniqlDbVersion] UNIQUE NONCLUSTERED ([Version] ASC)
2019-12-19T23:21:41.9495413Z 	                    );
2019-12-19T23:21:41.9495754Z 
2019-12-19T23:21:41.9495963Z 	                    ALTER TABLE [dbo].[__YuniqlDbVersion] ADD  CONSTRAINT [DF___YuniqlDbVersion_DateInsertedUtc]  DEFAULT (GETUTCDATE()) FOR [DateInsertedUtc];
2019-12-19T23:21:41.9496196Z 	                    ALTER TABLE [dbo].[__YuniqlDbVersion] ADD  CONSTRAINT [DF___YuniqlDbVersion_LastUpdatedUtc]  DEFAULT (GETUTCDATE()) FOR [LastUpdatedUtc];
2019-12-19T23:21:41.9496405Z 	                    ALTER TABLE [dbo].[__YuniqlDbVersion] ADD  CONSTRAINT [DF___YuniqlDbVersion_LastUserId]  DEFAULT (SUSER_SNAME()) FOR [LastUserId];
2019-12-19T23:21:41.9496614Z                     END                
2019-12-19T23:21:41.9496766Z             
2019-12-19T23:21:41.9497241Z DBG   2019-12-19T23:21:41.9486542Z   Executing sql statement: 
2019-12-19T23:21:41.9497390Z 
2019-12-19T23:21:41.9497552Z                     USE azsql-sandbox;
2019-12-19T23:21:41.9497687Z 
2019-12-19T23:21:41.9497856Z                     IF OBJECT_ID('[dbo].[__YuniqlDbVersion]') IS NULL 
2019-12-19T23:21:41.9498009Z                     BEGIN
2019-12-19T23:21:41.9498182Z 	                    CREATE TABLE [dbo].[__YuniqlDbVersion](
2019-12-19T23:21:41.9498500Z 		                    [Id] [SMALLINT] IDENTITY(1,1),
2019-12-19T23:21:41.9499011Z 		                    [Version] [NVARCHAR](32) NOT NULL,
2019-12-19T23:21:41.9499158Z 		                    [DateInsertedUtc] [DATETIME] NOT NULL,
2019-12-19T23:21:41.9499692Z 		                    [LastUpdatedUtc] [DATETIME] NOT NULL,
2019-12-19T23:21:41.9499852Z 		                    [LastUserId] [NVARCHAR](128) NOT NULL,
2019-12-19T23:21:41.9500017Z 		                    [Artifact] [VARBINARY](MAX) NULL,
2019-12-19T23:21:41.9500210Z 		                    CONSTRAINT [PK___YuniqlDbVersion] PRIMARY KEY CLUSTERED ([Id] ASC),
2019-12-19T23:21:41.9500370Z 		                    CONSTRAINT [IX___YuniqlDbVersion] UNIQUE NONCLUSTERED ([Version] ASC)
2019-12-19T23:21:41.9500544Z 	                    );
2019-12-19T23:21:41.9500658Z 
2019-12-19T23:21:41.9500817Z 	                    ALTER TABLE [dbo].[__YuniqlDbVersion] ADD  CONSTRAINT [DF___YuniqlDbVersion_DateInsertedUtc]  DEFAULT (GETUTCDATE()) FOR [DateInsertedUtc];
2019-12-19T23:21:41.9501023Z 	                    ALTER TABLE [dbo].[__YuniqlDbVersion] ADD  CONSTRAINT [DF___YuniqlDbVersion_LastUpdatedUtc]  DEFAULT (GETUTCDATE()) FOR [LastUpdatedUtc];
2019-12-19T23:21:41.9501224Z 	                    ALTER TABLE [dbo].[__YuniqlDbVersion] ADD  CONSTRAINT [DF___YuniqlDbVersion_LastUserId]  DEFAULT (SUSER_SNAME()) FOR [LastUserId];
2019-12-19T23:21:41.9501526Z                     END                
2019-12-19T23:21:41.9501683Z             
2019-12-19T23:21:42.1398160Z ERR   2019-12-19T23:21:42.1392778Z   Failed to execute run function. Target database will be rolled back to its previous state. 
2019-12-19T23:21:42.1398712Z System.Data.SqlClient.SqlException (0x80131904): USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
2019-12-19T23:21:42.1398966Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1399151Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1399346Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-12-19T23:21:42.1399550Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-12-19T23:21:42.1399760Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2019-12-19T23:21:42.1400687Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
2019-12-19T23:21:42.1400868Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-12-19T23:21:42.1401045Z    at Yuniql.SqlServer.SqlServerDataService.ConfigureDatabase()
2019-12-19T23:21:42.1401235Z    at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
2019-12-19T23:21:42.1401415Z    at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)
2019-12-19T23:21:42.1401581Z ClientConnectionId:a7e250e4-af40-4dff-93e6-e37341183551
2019-12-19T23:21:42.1401718Z Error Number:40508,State:1,Class:16
2019-12-19T23:21:42.1401879Z ClientConnectionId before routing:c7f25386-76d3-4215-9f1b-5df9ed9b9964
2019-12-19T23:21:42.1402032Z Routing Destination:d48794e4030e.tr4419.westeurope1-a.worker.database.windows.net,11026
2019-12-19T23:21:42.1402305Z ERR   2019-12-19T23:21:42.1392778Z   Failed to execute run function. Target database will be rolled back to its previous state. 
2019-12-19T23:21:42.1413173Z System.Data.SqlClient.SqlException (0x80131904): USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
2019-12-19T23:21:42.1413879Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1414118Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1414324Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-12-19T23:21:42.1414542Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-12-19T23:21:42.1414757Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2019-12-19T23:21:42.1415098Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
2019-12-19T23:21:42.1415277Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-12-19T23:21:42.1415418Z    at Yuniql.SqlServer.SqlServerDataService.ConfigureDatabase()
2019-12-19T23:21:42.1415811Z    at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
2019-12-19T23:21:42.1415997Z    at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)
2019-12-19T23:21:42.1416138Z ClientConnectionId:a7e250e4-af40-4dff-93e6-e37341183551
2019-12-19T23:21:42.1416301Z Error Number:40508,State:1,Class:16
2019-12-19T23:21:42.1416442Z ClientConnectionId before routing:c7f25386-76d3-4215-9f1b-5df9ed9b9964
2019-12-19T23:21:42.1416610Z Routing Destination:d48794e4030e.tr4419.westeurope1-a.worker.database.windows.net,11026
2019-12-19T23:21:42.1435214Z Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
2019-12-19T23:21:42.1435403Z Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): USE statement is not supported to switch between databases. Use a new connection to connect to a different database.
2019-12-19T23:21:42.1435754Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1435850Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1436436Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1436536Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-19T23:21:42.1436772Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-12-19T23:21:42.1436873Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-12-19T23:21:42.1437141Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-12-19T23:21:42.1437625Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-12-19T23:21:42.1438423Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2019-12-19T23:21:42.1438558Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2019-12-19T23:21:42.1438826Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
2019-12-19T23:21:42.1438978Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
2019-12-19T23:21:42.1439224Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-12-19T23:21:42.1439302Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-12-19T23:21:42.1439534Z    at Yuniql.SqlServer.SqlServerDataService.ConfigureDatabase()
2019-12-19T23:21:42.1439614Z    at Yuniql.SqlServer.SqlServerDataService.ConfigureDatabase()
2019-12-19T23:21:42.1439863Z    at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
2019-12-19T23:21:42.1439987Z    at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
2019-12-19T23:21:42.1440365Z    at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)
2019-12-19T23:21:42.1440447Z    at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)
2019-12-19T23:21:42.1440677Z    at Yuniql.Program.<>c__DisplayClass0_0.<Main>b__1(RunOption opts)
2019-12-19T23:21:42.1446406Z    at Yuniql.Program.<>c__DisplayClass0_0.<Main>b__1(RunOption opts)
2019-12-19T23:21:42.1449051Z    at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 notParsedFunc)
2019-12-19T23:21:42.1449279Z    at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 notParsedFunc)
2019-12-19T23:21:42.1454552Z    at Yuniql.Program.Main(String[] args)
2019-12-19T23:21:42.1454645Z    at Yuniql.Program.Main(String[] args)
2019-12-19T23:21:42.1456833Z ClientConnectionId:a7e250e4-af40-4dff-93e6-e37341183551
2019-12-19T23:21:42.1456929Z ClientConnectionId:a7e250e4-af40-4dff-93e6-e37341183551
2019-12-19T23:21:42.1547390Z Error Number:40508,State:1,Class:16
2019-12-19T23:21:42.1548505Z Error Number:40508,State:1,Class:16
2019-12-19T23:21:42.1648176Z ClientConnectionId before routing:c7f25386-76d3-4215-9f1b-5df9ed9b9964
2019-12-19T23:21:42.1648318Z ClientConnectionId before routing:c7f25386-76d3-4215-9f1b-5df9ed9b9964
2019-12-19T23:21:42.1653601Z Routing Destination:d48794e4030e.tr4419.westeurope1-a.worker.database.windows.net,11026
2019-12-19T23:21:42.1653723Z Routing Destination:d48794e4030e.tr4419.westeurope1-a.worker.database.windows.net,11026
2019-12-19T23:21:42.1655152Z 
2019-12-19T23:21:42.1715407Z ##[error]The process 'C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe' failed with exit code 3762504530
2019-12-19T23:21:42.1738740Z ##[section]Finishing: run
```

**Comment by rdagumampan** [comment]
Fix applied here and verified on Azure SqlDatabase https://github.com/rdagumampan/yuniql/commit/0a4dcbd76f2713d4ebcaf6ac106e51269ef1092f
