### ISSUE TITLE
error from microsoft devops hosted build agent. any ideas?

### ISSUE THREAD

**Issue by developertrudexia** [rdagumampan/yuniql#294]
ERR   2023-03-12 02:32:10Z   Failed to execute run function. NpgsqlTransaction
Diagnostics stack trace captured a System.ObjectDisposedException: 
 ---> Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|41_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Yuniql.Core.ConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.MetadataService.ExecuteSql(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.MigrationService.<>c__DisplayClass16_1.<RunVersionSqlScripts>b__3(String sqlStatement)
   at System.Collections.Generic.List`1.ForEach(Action`1 )
   at Yuniql.Core.MigrationService.<>c__DisplayClass16_0.<RunVersionSqlScripts>b__1(String scriptFile)
   at System.Collections.Generic.List`1.ForEach(Action`1 )
   at Yuniql.Core.MigrationService.RunVersionSqlScripts(IDbConnection connection, IDbTransaction transaction, TransactionContext transactionContext, Stopwatch stopwatch, String version, String workspace, String scriptDirectory, String metaSchemaName, String metaTableName, List`1 tokens, Nullable`1 commandTimeout, String environment, String appliedByTool, String appliedByToolVersion)
   --- End of inner exception stack trace ---
   at Npgsql..CheckDisposed()
   at Npgsql..CheckReady()
   at Npgsql..Rollback(Boolean async, CancellationToken cancellationToken)
   at Npgsql..Rollback()
   at Yuniql.Core.MigrationService.Run(String workspace, String targetVersion, Nullable`1 isAutoCreateDatabase, List`1 tokens, Nullable`1 isVerifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, Nullable`1 isContinueAfterFailure, String transactionMode, Boolean isRequiredClearedDraft)
   at Yuniql.Core.MigrationService.Run()
   at Yuniql.CLI.CommandLineService.RunRunOption(RunOption opts)

**Comment by rdagumampan** [comment]
@developertrudexia , have you found solution to this issue?

**Comment by tech7857** [comment]
@rdagumampan - We are also facing the same issue. Added commandtimeout also to the connection string but still no luck. Please assist
