### ISSUE TITLE
yuniql postgresql gis extenstion 

### ISSUE THREAD

**Issue by dnyandeobharambe** [rdagumampan/yuniql#295]
I am trying to deploy postgresql script where it have geospatial data . So it use corresponding data types. But it seems Yuniql does not support it and fail with following error

    SqlState: 42704
    MessageText: type "geometry" does not exist
    Position: 138
    File: parse_type.c
    Line: 275
    Routine: typenameType
   --- End of inner exception stack trace ---
   at Yuniql.Core.MigrationService.RunVersionSqlScripts(IDbConnection connection, IDbTransaction transaction, TransactionContext transactionContext, Stopwatch stopwatch, String version, String workspace, String scriptDirectory, String metaSchemaName, String metaTableName, List`1 tokens, Nullable`1 commandTimeout, String environment, String appliedByTool, String appliedByToolVersion)
   at Yuniql.Core.MigrationService.<>c__DisplayClass12_0.<RunVersionDirectories>g__RunVersionDirectoriesInternal|8(IDbConnection connection, IDbTransaction transaction, List`1 scriptSubDirectories, String scriptDirectory, String versionDirectory, Stopwatch stopwatch)
   at Yuniql.Core.MigrationService.<>c__DisplayClass12_0.<RunVersionDirectories>b__7(<>f__AnonymousType0`2 version)
   at System.Collections.Generic.List`1.ForEach(Action`1 )
   at Yuniql.Core.MigrationService.RunVersionDirectories(IDbConnection connection, IDbTransaction transaction, List`1 appliedVersions, String workspace, String targetVersion, TransactionContext transactionContext, List`1 tokens, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, String transactionMode)
   at Yuniql.Core.MigrationService.<Run>g__RunAllInternal|11_3(IDbConnection connection, IDbTransaction transaction, Boolean isRequiredClearedDraft, <>c__DisplayClass11_0& )
   at Yuniql.Core.MigrationService.Run(String workspace, String targetVersion, Nullable`1 isAutoCreateDatabase, List`1 tokens, Nullable`1 isVerifyOnly, String bulkSeparator, String metaSchemaName, String metaTableName, Nullable`1 commandTimeout, Nullable`1 bulkBatchSize, String appliedByTool, String appliedByToolVersion, String environment, Nullable`1 isContinueAfterFailure, String transactionMode, Boolean isRequiredClearedDraft)
   at Yuniql.Core.MigrationService.Run()
   at Yuniql.CLI.CommandLineService.RunRunOption(RunOption opts)
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.

yuniql/error: The process 'C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe' failed with exit code 1
##[error]The process 'C:\hostedtoolcache\windows\yuniql\0.0.0\x64\yuniql.exe' failed with exit code 1
Finishing: RunYuniqlCLI

**Comment by DavidPavlicek** [comment]
I have no problem with migration scripts containing PostGIS geomtery type. It looks like postgres does not know about geometry type. Did you enable PosGIS extension inside that database (create extension postgis;)?

**Comment by dnyandeobharambe** [comment]
Yes GIS extension is enabled

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DavidPavlicek** [comment]
Can yuniql user acces postgis function and types? If you login into database as the same user, can you `select 'POINT(1 1)'::geometry`?

**Comment by dnyandeobharambe** [comment]
let me check

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dnyandeobharambe** [comment]
I check and saw some weird,instance I set in azure with gis,show all gis data type like polygon,point but not geometry,that could be issue as data type of table I am creating is geometry

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dnyandeobharambe** [comment]
Thanks It was issue with extensions, I reenable it and it works well

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
