### ISSUE TITLE
Failed migration using Docker task in Azure DevOps

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#32]
```console
2019-12-21T20:14:22.2350020Z ##[section]Starting: run
2019-12-21T20:14:22.2355086Z ==============================================================================
2019-12-21T20:14:22.2355209Z Task         : Docker
2019-12-21T20:14:22.2355289Z Description  : Build or push Docker images, login or logout, or run a Docker command
2019-12-21T20:14:22.2355405Z Version      : 2.162.0
2019-12-21T20:14:22.2355471Z Author       : Microsoft Corporation
2019-12-21T20:14:22.2355569Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/docker
2019-12-21T20:14:22.2355658Z ==============================================================================
2019-12-21T20:14:23.2077824Z [command]/usr/bin/docker run visitph-example -c "XXXXXXXXX"
2019-12-21T20:14:24.0640047Z INF   2019-12-21T20:14:24.0603392Z   Started migration from db.
...
...
...
2019-12-21T20:14:25.8293130Z INF   2019-12-21T20:14:25.8286452Z   Found the 0 script files on db/v1.01
2019-12-21T20:14:25.8293421Z INF   2019-12-21T20:14:25.8287095Z   
2019-12-21T20:14:25.8293770Z INF   2019-12-21T20:14:25.8288013Z   Found the 0 bulk files on db/v1.01
2019-12-21T20:14:25.8294031Z INF   2019-12-21T20:14:25.8288797Z   
2019-12-21T20:14:25.8462526Z INF   2019-12-21T20:14:25.8456913Z   Completed migration to version db/v1.01
2019-12-21T20:14:25.8462920Z INF   2019-12-21T20:14:25.8458386Z   Found the 2 script files on db/_draft
2019-12-21T20:14:25.8463306Z INF   2019-12-21T20:14:25.8459311Z   02-initialize-destination-tables.sql\r\n\t01-setup-destination-tables.sql
2019-12-21T20:14:25.9001926Z ERR   2019-12-21T20:14:25.8976927Z   Failed to execute run function. Target database will be rolled back to its previous state. 
2019-12-21T20:14:25.9002708Z System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.Destination'.
2019-12-21T20:14:25.9003236Z    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-21T20:14:25.9003585Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2019-12-21T20:14:25.9003763Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2019-12-21T20:14:25.9004075Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2019-12-21T20:14:25.9004258Z    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
2019-12-21T20:14:25.9004401Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
2019-12-21T20:14:25.9005196Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2019-12-21T20:14:25.9005335Z    at Yuniql.SqlServer.SqlServerDataService.ExecuteNonQuery(IDbConnection activeConnection, String sqlStatement, IDbTransaction transaction)
2019-12-21T20:14:25.9005457Z    at Yuniql.Core.MigrationService.<>c__DisplayClass12_1.<RunNonVersionScripts>b__3(String sqlStatement)
2019-12-21T20:14:25.9005817Z    at System.Collections.Generic.List`1.ForEach(Action`1 action)
2019-12-21T20:14:25.9005964Z    at Yuniql.Core.MigrationService.<>c__DisplayClass12_0.<RunNonVersionScripts>b__1(String scriptFile)
2019-12-21T20:14:25.9006071Z    at System.Collections.Generic.List`1.ForEach(Action`1 action)
2019-12-21T20:14:25.9006225Z    at Yuniql.Core.MigrationService.RunNonVersionScripts(IDbConnection connection, IDbTransaction transaction, String directoryFullPath, List`1 tokens)
2019-12-21T20:14:25.9006366Z    at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
2019-12-21T20:14:25.9006519Z    at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)

**Comment by rdagumampan** [comment]
Fixed applied in https://github.com/rdagumampan/yuniql/commit/73a5051341fbe659ed0caf6920888cdc41fbb6e4
