### ISSUE TITLE
Failed to load plugin dependency using AssemblyLoadContext in .NET Core 3.0

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#46]
I have a plugin with failing dependencies though I tried to follow as much MS recommendation on .NET Core 3.0. Been trying to figure out whats the problem for 2 days already :/. Appreciate an input or where to look. Thanks!

Details:

- Entry point is a CLI app published by .NET Core 3.0 self-contained app
	```console
	//publishes as EXE file
	dotnet publish -c release -r win-x64 /p:publishsinglefile=true /p:publishtrimmed=true
	```
- Testing on Win-x64 and Linux-x64
- .NET Core 3.0 assemblies
- Plugin DLLs are published with this command

	```console
	//publishes as DLL files
	dotnet publish -c release -r linux-x64 /p:publishtrimmed=true -o ./app
	```

The logs shows that file is there, it exists but the dependency resolver failed to load it and throws a FileNotFoundException. Strange.

```console

C:\play\yuniql\yuniql-cli\bin\release\netcoreapp3.0\win-x64\publish>yuniql.exe run --plugins-path C:\temp\aztools\yuniql\0.0.0\x64\.plugins -p C:\play\yuniql\yuniql-plugins\postgresql\samples -c "Host=localhost;Port=5432;Username=xxx;Password=xxx;Database=yuniqldb" --platform postgresql -a 1 --debug
...
DBG   platformLowerCased: postgresql
DBG   pluginsPathParameter: C:\temp\aztools\yuniql\0.0.0\x64\.plugins
DBG   defaultAssemblyBasePath: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql
...
DBG   Found plugin dir: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql
DBG   Found plugin file: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Npgsql.dll. ProductVersion: 4.1.1, FileVersion: 4.1.1.0
DBG   Found plugin file: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Yuniql.Extensibility.dll. ProductVersion: 0.302.0, FileVersion: 0.302.0.0
DBG   Found plugin file: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Yuniql.PostgreSql.deps.json. ProductVersion: , FileVersion:
DBG   Found plugin file: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Yuniql.PostgreSql.dll. ProductVersion: 0.305.0, FileVersion: 0.305.0.0
DBG   Found plugin file: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Yuniql.PostgreSql.pdb. ProductVersion: , FileVersion:

DBG   pluginAssemblyFilePath: C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Yuniql.PostgreSql.dll
DBG   loadedAssembly: Yuniql.PostgreSql, Version=0.305.0.0, Culture=neutral, PublicKeyToken=null
DBG   retryResolving: Npgsql, Version=4.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7
DBG   failedAssemblyFileExists: True
DBG   attempting to reload Npgsql, Version=4.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7 via streaming from C:\temp\aztools\yuniql\0.0.0\x64\.plugins\postgresql\Npgsql.dll

ERR   Failed to execute run function. Target database will be rolled back to its previous state.
System.IO.FileNotFoundException: Could not load file or assembly 'Npgsql, Version=4.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'. The system cannot find the file specified.
File name: 'Npgsql, Version=4.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'
   at Yuniql.PostgreSql.PostgreSqlDataService.GetConnectionInfo()
   at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
   at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Npgsql, Version=4.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'. The system cannot find the file specified.
File name: 'Npgsql, Version=4.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'
   at Yuniql.PostgreSql.PostgreSqlDataService.GetConnectionInfo()
   at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Boolean autoCreateDatabase, List`1 tokenKeyPairs, Boolean verifyOnly, String delimeter)
   at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts)
   at Yuniql.Program.<>c__DisplayClass0_0.<Main>b__1(RunOption opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 notParsedFunc)
   at Yuniql.Program.Main(String[] args)
C:\play\yuniql\yuniql-cli\bin\release\netcoreapp3.0\win-x64\publish>
```

PluginAssemblyLoadContext
https://github.com/rdagumampan/yuniql/blob/master/yuniql-core/PluginAssemblyLoadContext.cs

```csharp
class PluginAssemblyLoadContext : AssemblyLoadContext
{
	private AssemblyDependencyResolver _resolver;

	public PluginAssemblyLoadContext(string pluginPath) : base(isCollectible: true)
	{
		_resolver = new AssemblyDependencyResolver(pluginPath);
	}
	protected override Assembly Load(AssemblyName name)
	{
		string assemblyPath = _resolver.ResolveAssemblyToPath(name);
		if (assemblyPath != null)
		{
			Console.WriteLine($"Loading assembly {assemblyPath} into the HostAssemblyLoadContext");
			return LoadFromAssemblyPath(assemblyPath);
		}

		return null;
	}
}
```

Load plugin from /app/.plugins/PostgreSql
https://github.com/rdagumampan/yuniql/blob/master/yuniql-core/MigrationServiceFactory.cs

```csharp
// create the unloadable HostAssemblyLoadContext
var pluginAssemblyLoadContext = new PluginAssemblyLoadContext(pluginAssemblyBasePath);

//the plugin assembly into the HostAssemblyLoadContext. 
//the assemblyPath must be an absolute path.
var assembly = pluginAssemblyLoadContext.LoadFromAssemblyPath(pluginAssemblyFilePath);
pluginAssemblyLoadContext.Assemblies
	.ToList()
	.ForEach(a =>
	{
		_traceService.Debug($"loadedAssembly: {a.FullName}");
	});
pluginAssemblyLoadContext.Resolving += AssemblyContext_Resolving;
pluginAssemblyLoadContext.Unloading += AssemblyContext_Unloading;

var sqlDataService = assembly.GetTypes()
	.Where(t => t.Name.ToLower().Contains($"{platformLowerCased.ToLower()}dataservice"))
	.Select(t => Activator.CreateInstance(t, _traceService))
	.Cast<IDataService>()
	.First();

var bulkImportService = assembly.GetTypes()
	.Where(t => t.Name.ToLower().Contains($"{platformLowerCased.ToLower()}bulkimportservice"))
	.Select(t => Activator.CreateInstance(t, _traceService))
	.Cast<IBulkImportService>()
	.First();

var tokenReplacementService = new TokenReplacementService(_traceService);

var migrationService = new MigrationService(sqlDataService, bulkImportService, tokenReplacementService, directoryService, fileService, _traceService);
return migrationService;
```

Attempt to force resolve

```csharp
private System.Reflection.Assembly AssemblyContext_Resolving(System.Runtime.Loader.AssemblyLoadContext assemblyContext, System.Reflection.AssemblyName failedAssembly)
{
	var pluginAssemblyLoadContext = assemblyContext as PluginAssemblyLoadContext;
	_traceService.Debug($"retryResolving: {failedAssembly.FullName}");

	var assemblyFilePath = Path.Combine(pluginAssemblyLoadContext.PluginPath, failedAssembly.Name + ".dll");
	_traceService.Debug($"failedAssemblyFileExists: {File.Exists(assemblyFilePath)}");

	using (var file = File.Open(assemblyFilePath, FileMode.Open, FileAccess.Read, FileShare.Read))
	{
		_traceService.Debug($"attempting to reload {failedAssembly.FullName} via streaming from {assemblyFilePath}");
		pluginAssemblyLoadContext.LoadFromStream(file);
	}

	//assemblyContext.LoadFromAssemblyPath(assemblyFilePath);
	//assemblyContext.LoadFromAssemblyName(new System.Reflection.AssemblyName(failedAssembly.Name));

	return null;
}
```

UPDATE 12/26/2019: I thought it was an issue only to linux but I was able to reproduce in Windows. Interestingly, when I run my platform tests which calls the Factory class directly but still the factory uses the AssemblyLoadContext, it works OK!.

The difference, it fails when called by CLI (a .NET Core 3.0 selfcontained EXE app) but OK when called from VSTestRunner (MSTEST).

**Comment by rdagumampan** [comment]
The issue has been resolved by implementing a fall back dependency resolution mechanism in the AssemblyLoadContext. But I have decided not to perform dynamic loading anyway because it has other issues when loading plugins in self-contained .NET 3.0 app.

See https://github.com/rdagumampan/yuniql/blob/master/yuniql-core/PluginAssemblyLoadContext.cs
```csharp
   protected override Assembly Load(AssemblyName assemblyName)
        {
            if (null == assemblyName.Name) return null;

            try
            {
                var assembly = _defaultLoadContext.LoadFromAssemblyName(assemblyName);
                if (null != assembly)
                {
                    return assembly;
                }
            }
            catch (Exception)
            {
                string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
                _traceService.Debug($"Resolving dependency: {assemblyName.Name}, v{assemblyName.Version} from componentAssemblyPath: {PluginPath}");

                if (assemblyPath != null)
                {
                    _traceService.Debug($"Resolved dependency. Loading {assemblyPath} into the PluginAssemblyLoadContext");
                    return LoadFromAssemblyPath(assemblyPath);
                }
                else
                {
                    _traceService.Debug($"Failed resolving dependency: {assemblyName.Name}, v{assemblyName.Version}");
                }
            }

            return null;
        }
```
