### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#68]
Failed migration when running migration via YAML Pipelines and CommandLine Task

> Failed to execute run function. Target database will be rolled back to its previous state. 
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'D:\a\1\s\'D:\a\1\s\O.WP.Service.Database''

### Task: install yuniql
```console
dotnet tool install -g yuniql.cli
yuniql version
```

### Task: run db migration
```console
Starting: migrate db with yuniql
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
yuniql run -p 'D:\a\1\s\O.WP.Service.Database' -c '***' --debug
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\440076bd-d53a-4a16-8123-2b7b523738b9.cmd""
INF   2020-04-07T22:05:19.6551934Z   Started migration from 'D:\a\1\s\O.WP.Service.Database'.
ERR   2020-04-07T22:05:19.6848663Z   Failed to execute run function. Target database will be rolled back to its previous state. 
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'D:\a\1\s\'D:\a\1\s\O.WP.Service.Database''
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern)
   at Yuniql.Core.LocalVersionService.GetLocalVersions(String workingPath) in C:\projects\yuniql\yuniql-core\LocalVersionService.cs:line 150
   at Yuniql.Core.LocalVersionService.GetLatestVersion(String workingPath) in C:\projects\yuniql\yuniql-core\LocalVersionService.cs:line 177
   at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts) in C:\projects\yuniql\yuniql-cli\CommandLineService.cs:line 108
Unhandled exception. System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'D:\a\1\s\'D:\a\1\s\O.WP.Service.Database''
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern)
   at Yuniql.Core.LocalVersionService.GetLocalVersions(String workingPath) in C:\projects\yuniql\yuniql-core\LocalVersionService.cs:line 150
   at Yuniql.Core.LocalVersionService.GetLatestVersion(String workingPath) in C:\projects\yuniql\yuniql-core\LocalVersionService.cs:line 177
   at Yuniql.CLI.CommandLineService.RunMigration(RunOption opts) in C:\projects\yuniql\yuniql-cli\CommandLineService.cs:line 108
   at Yuniql.Program.<>c__DisplayClass0_0.<Main>b__1(RunOption opts) in C:\projects\yuniql\yuniql-cli\Program.cs:line 38
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 notParsedFunc)
   at Yuniql.Program.Main(String[] args) in C:\projects\yuniql\yuniql-cli\Program.cs:line 71
##[error]Cmd.exe exited with code '-532462766'.
Finishing: migrate db with yuniql
```

**Comment by rdagumampan** [comment]
Resolved. When configuring via YAML pipelines, always use double quote to pass the parameters such as `-c`  connection string and `-p` Path.

```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #name: 'DnD ART NonProduction - Windows'
  vmImage: 'vs2017-win2016'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.0.103'
  inputs:
    packageType: 'sdk'
    version: '3.0.103'

- task: CmdLine@2
  displayName: 'install yuniql'
  inputs:
    script: |
      dotnet tool install -g yuniql.cli
      yuniql version
- task: CmdLine@2
  displayName: 'migrate db with yuniql'
  inputs:
    script: |
      yuniql run -p "$(Build.SourcesDirectory)\O.WP.Service.Database" -c "$(AzSqlDatabase)" --debug
```
