### ISSUE TITLE
Friendly error message instead of stacktrace

### ISSUE THREAD

**Issue by farazfaheem** [rdagumampan/yuniql#70]
When there is an error in the script, it shows the whole stacktrace.  It should be better if I could see only friendly error messages. 

PS C:\Users\muhfa\DSS\WFSDH\POPE> YUNIQL verify
INF   2020-04-15T08:37:10.0502437Z   Started verifcation from C:\Users\...
INF   2020-04-15T08:37:10.1164219Z   No explicit target version requested. We'll use latest available locally v0.02 on C:\Users\...
INF   2020-04-15T08:37:10.8242608Z   Found the 1 script files on C:\Users\..\_pre
INF   2020-04-15T08:37:10.8273411Z   script.sql
ERR   2020-04-15T08:37:10.9107091Z   Failed to execute verification function. Target database will be rolled back to its previous state.
System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Table_11'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Yuniql.Core.ConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.ConfigurationDataService.ExecuteSql(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.MigrationService.<>c__DisplayClass14_1.<RunNonVersionScripts>b__3(String sqlStatement)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.<>c__DisplayClass14_0.<RunNonVersionScripts>b__1(String scriptFile)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.RunNonVersionScripts(IDbConnection connection, IDbTransaction transaction, String workingPath, List`1 tokenKeyPairs, String delimiter, Nullable`1 commandTimeout, String environmentCode)
   at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Nullable`1 autoCreateDatabase, List`1 tokenKeyPairs, Nullable`1 verifyOnly, String delimiter, Nullable`1 commandTimeout, Nullable`1 batchSize, String appliedByTool, String appliedByToolVersion, String environmentCode)
   at Yuniql.CLI.CommandLineService.RunVerify(VerifyOption opts)
ClientConnectionId:857baaf5-31ce-49ec-bad0-6a4c1f149c56
Error Number:208,State:1,Class:16
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Table_11'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Yuniql.Core.ConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.ConfigurationDataService.ExecuteSql(IDbConnection connection, String commandText, Nullable`1 commandTimeout, IDbTransaction transaction, ITraceService traceService)
   at Yuniql.Core.MigrationService.<>c__DisplayClass14_1.<RunNonVersionScripts>b__3(String sqlStatement)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.<>c__DisplayClass14_0.<RunNonVersionScripts>b__1(String scriptFile)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Yuniql.Core.MigrationService.RunNonVersionScripts(IDbConnection connection, IDbTransaction transaction, String workingPath, List`1 tokenKeyPairs, String delimiter, Nullable`1 commandTimeout, String environmentCode)
   at Yuniql.Core.MigrationService.Run(String workingPath, String targetVersion, Nullable`1 autoCreateDatabase, List`1 tokenKeyPairs, Nullable`1 verifyOnly, String delimiter, Nullable`1 commandTimeout, Nullable`1 batchSize, String appliedByTool, String appliedByToolVersion, String environmentCode)
   at Yuniql.CLI.CommandLineService.RunVerify(VerifyOption opts)
   at Yuniql.Program.<>c__DisplayClass0_0.<Main>b__4(VerifyOption opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 notParsedFunc)
   at Yuniql.Program.Main(String[] args)
ClientConnectionId:857baaf5-31ce-49ec-bad0-6a4c1f149c56

**Comment by rdagumampan** [comment]
Sounds like a good idea @farazfaheem. Perhaps I will only show the error message under normal execution but still show these when `--debug` is activated.

**Comment by farazfaheem** [comment]
> Sounds like a good idea @farazfaheem. Perhaps I will only show the error message under normal execution but still show these when `--debug` is activated.

That's fine. 👍

**Comment by rdagumampan** [comment]
Done. @Jabestrada thanks for your contribution!

```bash
ERR   2020-06-01T20:54:21.5248721Z   Failed to execute run function. Arrg... something seems broken. 
Error message: Unable to connect to any of the specified MySQL hosts. One or more errors occurred. (No such host is known.) 
If you think this is a bug, please report issue https://github.com/rdagumampan/yuniql/issues.
```
